version: '3.8'

services:
  ollama_server:
    image: ollama/ollama
    container_name: ollama_server
    ports:
      - "3101:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3100:8080"
    env_file:
      - .env
    environment:
      - OLLAMA_BASE_URL=http://ollama_server:11434
      - OPENAI_API_BASE_URLS
      - OPENAI_API_KEYS
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama_server
    restart: unless-stopped

volumes:
  ollama:
    external: true
  open-webui:
    external: true
